### ISSUE TITLE
Move or fix scripts for substages

### ISSUE THREAD

**Issue by LukasNickel** [cta-observatory/lstmcpipe#104]
Currently it is expected to use the `onsite_mc_r0_to_dl3` for all stages.
Thats not really apparent from the naming and if the other scripts are not meant to be used independently, they probably dont need that much argparse boiler code

**Comment by garciagenrique** [comment]
Hi @LukasNickel (let's start with the easy ones).

Originally all the stages (and thus each `onsite_*`) were meant to be run independently. Later the workflow evolved, and all the stages were modified so that they could be run in both modes, independently and within a workflow. 

The amount of argparse arguments that are passed between all the stages is because of this - although not updated since time ago.

**Comment by garciagenrique** [comment]
This is part of a larger problem, imho. How can you do (in an optimal way) a bunch of scripts that can be run independently and as part of a workflow ? The solution that I found was;
 
 - Separate the independent and the workflow scripts 
    - Pro: would simplify the reading and understanding of the workflow
    - Con: would introduce a lot of duplicated code into the repository (thus double work/time to maintain)

- Users really use the independent scripts to run/launch individual stages ? Is this functionality really needed in this project or it can be removed ?

**Comment by LukasNickel** [comment]
I dont really know which way I prefer.
But do you really think there would be a lot of duplicated code? Things like selecting files etc could just be placed in a function, that is then imported in each file.

**Comment by garciagenrique** [comment]
Partially solving this in #121.
Any suggestion to rename `onsite_mc_r0_to_dl3.py` ? `lstmcpipe_start` ? `lstmcpipe_launcher` ? other ?

**Comment by LukasNickel** [comment]
`lstmcpipe-process` ?
