### ISSUE TITLE
DL2 training files produced

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/lstmcpipe#135]
Hi
Looking at last productions, I saw that DL2 *training* files are produced  and it is not clear to me why is that. RF are trained on DL1, only DL2 test files should be produced, no?

**Comment by moralejo** [comment]
Indeed, I had also seen some train/DL2 files around but forgot to report it. DL2 train files are even dangerous because the performance in them should be significantly better than in test files and in real data. And there will be nothing inside the files indicating they were part of the training sample.

**Comment by garciagenrique** [comment]
Thanks for opening an issue ! Indeed you are both right, will solve it asap.
