### ISSUE TITLE
Need to update lstchain config file for DL1AB processing

### ISSUE THREAD

**Issue by chaimain** [cta-observatory/lstmcpipe#160]
The lstchain config file https://github.com/cta-observatory/lstmcpipe/blob/master/lstmcpipe/standard_configs/lstchain_standard_config_v091.json does not include the MC tuning (PSF and NSB) information as written in https://github.com/cta-observatory/cta-lstchain/blob/master/lstchain/data/lstchain_dl1ab_tune_MC_to_Crab_config.json.

This is essential as this is THE information required for DL1AB processing.

**Comment by maxnoe** [comment]
But that is only for the specific crab data from November 2021. It's not valid for most data. 

Using it for everything is not possible and the discussion how to provide proper models for all data only started in the last analysis call.


So just including the crab config is I think not the way to go.

**Comment by chaimain** [comment]
Yes. We do not need to tune the NSB based on Crab for general purpose, but for PSF tuning, we can do that, right?

@moralejo mentioned that we can have the NSB tuning turned to False, and then proceed with PSF tuning

**Comment by chaimain** [comment]
For NSB tuning, we can probably have 1 set for Crab at least for now. I am not sure, how we will define 'standard config', as it is part of a larger discussion.

**Comment by moralejo** [comment]
Yes, we have to decide what to do regarding NSB tuning, especially once we have the new MC.

As of now, using the same NSB for all (be it dark or Crab) will anyway be less of a problem than using a single pointing for data taken with different pointings. Using Crab's NSB has the advantage that we get the best possible MC for the analysis of our standard candle - of course, not for the rest of sources.

PSF is a different story, because the default one in MC is too good, so I would definitely apply the PSF tuning to the MC for the analysis of any of the LST data we have taken so far.
