### ISSUE TITLE
Error config generator using AllSky production pipeline stage DL1ab

### ISSUE THREAD

**Issue by aaguasca** [cta-observatory/lstmcpipe#290]
Dear developers, an error appears when I try to create the configuration files using `lstmcpipe_generate_config` command for the AllSky production pipeline stage DL1ab using the terminal.

I am using the up-to-date lstmcpipe_dev environment on the cluster. I used the following command to create the configuration files:
`lstmcpipe_generate_config PathConfigAllSkyFullDL1ab --dec_list dec_2276 --prod_id 20220523_tuned --source_prod_id 20220511_allsky_std`

But the following error appears:
```
usage: lstmcpipe_generate_config [-h] [--prod_id PROD_ID] [--output OUTPUT]
                                 [--overwrite] [--lstchain_conf LSTCHAIN_CONF]
                                 [--dec_list DEC_LIST [DEC_LIST ...]]
                                 [--kwargs [KWARGS [KWARGS ...]]]
                                 config_class
lstmcpipe_generate_config: error: unrecognized arguments: --source_prod_id 20220511_allsky_std
```

**Comment by aaguasca** [comment]
The error is solved if I use `--kwargs source_prod_id=20220511_allsky_std` instead of `--source_prod_id 20220511_allsky_std`.

Thank you, Thomas, for the demo :)

**Comment by moralejo** [comment]
I just ran into the same problem, and it is not clear why a different keyword is used for DL1ab-only configs

**Comment by vuillaut** [comment]
Hi
Technically, that's because `source_prod_id` is not a generic input of `lstmcpipe_generate_config`.
The command has some input that is required for any type of production and then config specifics can be passed through kwargs.
I don't think the documentation ever mentions `--source_prod_id` ?
However, if that's confusing for many users, I will think of a work around.
